// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package broker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BrokerFulcrumServiceClient is the client API for BrokerFulcrumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerFulcrumServiceClient interface {
	RequestServer(ctx context.Context, in *ServerReq, opts ...grpc.CallOption) (*ServerResp, error)
}

type brokerFulcrumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerFulcrumServiceClient(cc grpc.ClientConnInterface) BrokerFulcrumServiceClient {
	return &brokerFulcrumServiceClient{cc}
}

func (c *brokerFulcrumServiceClient) RequestServer(ctx context.Context, in *ServerReq, opts ...grpc.CallOption) (*ServerResp, error) {
	out := new(ServerResp)
	err := c.cc.Invoke(ctx, "/BF.BrokerFulcrumService/RequestServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerFulcrumServiceServer is the server API for BrokerFulcrumService service.
// All implementations must embed UnimplementedBrokerFulcrumServiceServer
// for forward compatibility
type BrokerFulcrumServiceServer interface {
	RequestServer(context.Context, *ServerReq) (*ServerResp, error)
	mustEmbedUnimplementedBrokerFulcrumServiceServer()
}

// UnimplementedBrokerFulcrumServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerFulcrumServiceServer struct {
}

func (UnimplementedBrokerFulcrumServiceServer) RequestServer(context.Context, *ServerReq) (*ServerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestServer not implemented")
}
func (UnimplementedBrokerFulcrumServiceServer) mustEmbedUnimplementedBrokerFulcrumServiceServer() {}

// UnsafeBrokerFulcrumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerFulcrumServiceServer will
// result in compilation errors.
type UnsafeBrokerFulcrumServiceServer interface {
	mustEmbedUnimplementedBrokerFulcrumServiceServer()
}

func RegisterBrokerFulcrumServiceServer(s grpc.ServiceRegistrar, srv BrokerFulcrumServiceServer) {
	s.RegisterService(&BrokerFulcrumService_ServiceDesc, srv)
}

func _BrokerFulcrumService_RequestServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerFulcrumServiceServer).RequestServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BF.BrokerFulcrumService/RequestServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerFulcrumServiceServer).RequestServer(ctx, req.(*ServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerFulcrumService_ServiceDesc is the grpc.ServiceDesc for BrokerFulcrumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerFulcrumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BF.BrokerFulcrumService",
	HandlerType: (*BrokerFulcrumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestServer",
			Handler:    _BrokerFulcrumService_RequestServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BF.proto",
}
